/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.g16207.terekhov.lab1;


import lombok.Data;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

@Data
public class App {
    private static final Logger logger = LogManager.getLogger(App.class.getName());

    public String getGreeting() {
        return "Processing stats was started.";
    }


    public static void main(String[] args) {
        App app = new App();
        app.getGreeting();

    }
}
